# Site settings
author: Indira 
title: Indy, the coder
header-img: img/home-bg.png
email: indirak@alumni.princeton.edu
copyright_name: Indira 
description: > # this means to ignore newlines until "baseurl:"
  A dive into software engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  indykiss

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
